### ISSUE TITLE
Toc Dispaly Position Error

### ISSUE THREAD

**Issue by CN-Robert-LIU** [TonyChenn/hexo-theme-mdm#1]
If create toc for block, can't show the toc's suitable postion. Please check the style with class name as post-toc. (./layout/post.ejs)Thks

**Comment by TonyChenn** [comment]
> If create toc for block, can't show the toc's suitable postion. Please check the style with class name as post-toc. (./layout/post.ejs)Thks

I'm so sorry that, post-toc is still have some problems. and I'll solve them one by one. thanks for  your feedback.
