### ISSUE TITLE
搜索

### ISSUE THREAD

**Issue by 407374** [TonyChenn/hexo-theme-mdm#2]
有搜索功能就更好啦！

**Comment by TonyChenn** [comment]
因为搜索功能需要安装插件，mdm主题要打造轻盈，尽可能不依赖插件的主题，所以一直没有找到更好的解决方法。

**Comment by TonyChenn** [comment]
> 有搜索功能就更好啦！

因为搜索功能需要安装插件，mdm主题要打造轻盈，尽可能不依赖插件的主题，所以一直没有找到更好的解决方法。

**Comment by TonyChenn** [comment]
后续会添加，谢谢
